config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

src/Model/Entity/Instance.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Instance Entity
 *
 * @property int $id
 * @property string $name
 * @property string $rut_enterprises
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property int $type_enterprises
 * @property int $type_turn
 * @property string $contacts
 * @property \Cake\I18n\FrozenTime $date
 */
class Instance extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'name' => true,
        'rut_enterprises' => true,
        'email' => true,
        'phone' => true,
        'address' => true,
        'type_enterprises' => true,
        'type_turn' => true,
        'contacts' => true,
        'date' => true
    ];
}

src/Model/Table/InstancesTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Instances Model
 *
 * @method \App\Model\Entity\Instance get($primaryKey, $options = [])
 * @method \App\Model\Entity\Instance newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Instance[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Instance|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Instance|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Instance patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Instance[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Instance findOrCreate($search, callable $callback = null, $options = [])
 */
class InstancesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('instances');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->belongsTo('Type_instances', [
            'foreignKey' => 'type_instances',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Users',[
            'foreignKey' => 'instances_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('name')
            ->maxLength('name', 30)
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        // $validator
        //     ->scalar('rut_enterprises')
        //     ->maxLength('rut_enterprises', 40)
        //     ->requirePresence('rut_enterprises', 'create')
        //     ->notEmpty('rut_enterprises');

        // $validator
        //     ->email('email')
        //     ->requirePresence('email', 'create')
        //     ->notEmpty('email');

        // $validator
        //     ->scalar('phone')
        //     ->maxLength('phone', 40)
        //     ->requirePresence('phone', 'create')
        //     ->notEmpty('phone');

        // $validator
        //     ->scalar('address')
        //     ->maxLength('address', 30)
        //     ->requirePresence('address', 'create')
        //     ->notEmpty('address');

       /* $validator
            ->integer('type_enterprises')
            ->requirePresence('type_enterprises', 'create')
            ->notEmpty('type_enterprises');

        $validator
            ->integer('type_turn')
            ->requirePresence('type_turn', 'create')
            ->notEmpty('type_turn');*/

        $validator
            ->scalar('contacts')
            ->maxLength('contacts', 30)
            ->requirePresence('contacts', 'create')
            ->notEmpty('contacts');

       /* $validator
            ->dateTime('date')
            ->requirePresence('date', 'create')
            ->notEmpty('date');*/

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->isUnique(['type_instances'], 'Type_instances'));

        return $rules;
    }
}

src/Controller/InstancesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Instances Controller
 *
 * @property \App\Model\Table\InstancesTable $Instances
 *
 * @method \App\Model\Entity\Instance[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class InstancesController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $instances = $this->paginate($this->Instances);
        $titleForLayout= 'Instancias';
        $breadCrumb= 'Inicio';

        $this->set(compact('instances', 'titleForLayout', 'breadCrumb'));
    }

    /**
     * View method
     *
     * @param string|null $id Instance id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $instance = $this->Instances->get($id, [
            'contain' => ['Users', 'Type_instances']
        ]);
        //pr($instance); die;
        $this->paginate($this->Instances);
        $titleForLayout= 'Instancias';
        $breadCrumb= 'Vista';

        $this->set(compact('instance', $instance, 'titleForLayout', 'breadCrumb'));
        $this->Instances->find();
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $instance = $this->Instances->newEntity();
        if ($this->request->is('post')) {
            $instance = $this->Instances->patchEntity($instance, $this->request->getData());
            if ($this->Instances->save($instance)) {
                $this->Flash->success(__('La intancia se a guardado correctamente.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('La intancia no pudo guardarce. Intentelo nuevamente.'));
        }
        $titleForLayout= 'Instancias';
        $breadCrumb= 'Agregar';
        $this->set(compact('instance', 'titleForLayout', 'breadCrumb'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Instance id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $instance = $this->Instances->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $instance = $this->Instances->patchEntity($instance, $this->request->getData());
            if ($this->Instances->save($instance)) {
                $this->Flash->success(__('La intancia se pudo editar correctamente.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('La intancia no pudo editarce. Intentelo nuevamente.'));
        }
        $titleForLayout= 'Instancias';
        $breadCrumb= 'Editar';
        $this->set(compact('instance', 'titleForLayout', 'breadCrumb'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Instance id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $instance = $this->Instances->get($id);
        if ($this->Instances->delete($instance)) {
            $this->Flash->success(__('La intancia a sio eliminada correctamente.'));
        } else {
            $this->Flash->error(__('La intancia no pudo eliminarce. Intentelo nuevamente.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Instances/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Instance $instance
 */
?>

<!--div class="instances form large-9 medium-8 columns content">
    <?= $this->Form->create($instance) ?>
    <fieldset>
        <legend><?= __('Add Instance') ?></legend>
        <?php
            echo $this->Form->control('name');
            echo $this->Form->control('rut_enterprises');
            echo $this->Form->control('email');
            echo $this->Form->control('phone');
            echo $this->Form->control('address');
            echo $this->Form->control('type_instances');
            echo $this->Form->control('type_turn');
            echo $this->Form->control('contacts');
            echo $this->Form->control('date');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div-->



<div class="row">
    <div class="col-md-3 col-md-push-9">
        <div class="box box-info"><!-- Acciones -->
            <div class="box-header with-border">
                <h3 class="box-title">Acciones</h3>
            </div>
                <?= $this->Form->create($instance) ?>
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="btn-toolbar">
                        <?= $this->Html->link('<i class="fa fa-repeat fa-side"></i> Volver a la Lista',['controller' => 'instances', 'action' => 'index'],['class' => 'btn btn-info option', 'escape' => false])?>
                    <?= $this->Form->button(__('<i class="fa fa-save fa-side"></i>   Guardar'), ['class' => 'btn btn-info option'],['escape' => false]); ?>
                        </div>        
                    </div>
                </div>
            </div>
        </div>
    </div>

<div class="col-md-9 col-md-pull-3">
    <div class="box box-info">
        <div class="box-header with-border">
                <h3 class="box-title">Agregar Instancia</h3>
        </div>  
        <div class="box-body">
            <div class="row"><!--fila 1 -->
                <div class="col-md-4">
                    <? echo $this->Form->control('name', ['class' => 'form-control', 'label' => 'Nombre']);?>
                </div>
                <div class="col-md-4">
                    <? echo $this->Form->control('rut_enterprises', ['class' => 'form-control', 'label' => 'Rut de la empresa']);?>
                </div>
                <div class="col-md-4">
                    <? echo $this->Form->control('email', ['class' => 'form-control', 'label' => 'Email']);?>
                </div>
        </div>
    <br>
        <div class="row"> <!--fila 2 -->
                <div class="col-md-4">
                    <? echo $this->Form->control('phone', ['class' => 'form-control', 'label' => 'Telefono']);?>
                </div>
                <div class="col-md-4">
                    <? echo $this->Form->control('address', ['class' => 'form-control', 'label' => 'Dirección']);?>
                </div>
                <!-- <div class="col-md-4">
                    <? echo $this->Form->control('type_turn', ['class' => 'form-control', 'label' => 'Descripción']);?>
                </div> -->
        </div>    
    <br>
        <div class="row"><!-- fila 3 -->
                <div class="col-md-4">
                    <? echo $this->Form->control('type_instances', ['class' => 'form-control','label' => 'Tipo de instancia']);?>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <? echo $this->Form->control('contacts', ['class' => 'form-control','label' => 'Contactos']);?>
                    </div>
                </div>
                <div class="col-md-4 col-precio">
                    <? echo $this->Form->control('date', ['class' => 'form-control','label' => 'Fecha']);?>
                </div>
        </div>
    </div>
</div>
        <?= $this->Form->end() ?>
    

src/Template/Instances/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Instance $instance
 */
?>

<!--div class="instances form large-9 medium-8 columns content">
    <?= $this->Form->create($instance) ?>
    <fieldset>
        <legend><?= __('Edit Instance') ?></legend>
        <?php
            echo $this->Form->control('name');
            echo $this->Form->control('rut_enterprises');
            echo $this->Form->control('email');
            echo $this->Form->control('phone');
            echo $this->Form->control('address');
            echo $this->Form->control('type_instances');
            echo $this->Form->control('type_turn');
            echo $this->Form->control('contacts');
            echo $this->Form->control('date');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div-->



<div class="row">
    <div class="col-md-3 col-md-push-9">
        <div class="box box-info"><!-- Acciones -->
            <div class="box-header with-border">
                <h3 class="box-title">Acciones</h3>
            </div>
                <?= $this->Form->create($instance) ?>
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="btn-toolbar">
                        <?= $this->Html->link('<i class="fa fa-repeat fa-side"></i> Volver a la Lista',['controller' => 'instances', 'action' => 'index'],['class' => 'btn btn-info option', 'escape' => false])?>
                    <?= $this->Form->button(__('<i class="fa fa-save fa-side"></i>   Guardar'), ['class' => 'btn btn-info option'],['escape' => false]); ?>
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-9 col-md-pull-3">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Agregar Usuario</h3>
            </div>
                <div class="box-body">
                    <div class="row"><!--fila 1 -->
                        <div class="col-md-4">
                            <? echo $this->Form->control('name', ['class' => 'form-control','label' => 'Nombre']);?>
                        </div>
                        <div class="col-md-4">
                            <? echo $this->Form->control('rut_enterprises', ['class' => 'form-control','label' => 'Rut de empresa']);?>
                        </div>
                        <div class="col-md-4">
                            <? echo $this->Form->control('email', ['class' => 'form-control','label' => 'Email']);?>
                        </div>
                    </div>
                    <br>    
                    <div class="row"> <!--fila 2 -->
                        <div class="col-md-4">
                            <? echo $this->Form->control('phone', ['class' => 'form-control','label' => 'Telefono']);?>
                        </div>
                        <div class="col-md-4">
                            <? echo $this->Form->control('address', ['class' => 'form-control','label' => 'Dirección']);?>
                        </div>
                        <!-- <div class="col-md-4">
                            <? echo $this->Form->control('type_turn', ['class' => 'form-control','label' => 'Descripción']);?>
                        </div> -->
                    </div>    
                    <br>
                    <div class="row"><!-- fila 3 -->
                        <div class="col-md-4">
                            <? echo $this->Form->control('type_instances', ['class' => 'form-control','label' => 'Tipo de intancia']);?>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <? echo $this->Form->control('contacts', ['class' => 'form-control','label' => 'Contacto']);?>
                            </div>
                        </div>
                        <div class="col-md-4 col-precio">
                            <? echo $this->Form->control('date', ['class' => 'form-control','label' => 'Fecha']);?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                <?= $this->Form->end() ?>

src/Template/Instances/index.ctp
<div class="row">
<div class="row">
    <div class="col-lg-4 col-xs-4">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h4>Agrega Una Nueva Instancia</h4>
                <p>Aqui puedes agregar una <br> nueva instancia</p>
            </div>
            <div class="icon">
                <i class="far fa-building"></i>
            </div>
            <a href="#" class="">
                <?= $this->Html->link('<i class="fa fa-arrow-circle-right"></i> Agregar Nueva instancia ', ['controller'=>'instances', 'action'=>'add'], ['escape'=>false, 'class' => 'small-box-footer']); ?>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-4">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h4>Usuarios</h4>
                <p>Aqui puedes puedes ver <br> todos los Usuarios</p>
            </div>
            <div class="icon">
                <i class="far fa-user"></i>
            </div>
            <a href="#" class="small-box-footer">
                <?= $this->Html->link('<i class="fa fa-arrow-circle-right"></i> Ver Usuarios ', ['controller'=>'requeriments', 'action'=>'index'], ['escape'=>false, 'class' => 'small-box-footer']); ?>

            </a>
        </div>
    </div>
    <div class="col-lg-4 col-xs-4">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h4>Ordenes de Trabajo</h4>
                <p>Aqui puedes puedes ver <br> todos tus Ordenes de Trabajo</p>
            </div>
            <div class="icon">
                <i class="fas fa-tags"></i>
            </div>
            <a href="#" class="small-box-footer">
                <?= $this->Html->link('<i class="fa fa-arrow-circle-right"></i> Ver Ordenes de Trabajo ', ['controller'=>'WorkOrders', 'action'=>'index'], ['escape'=>false, 'class' => 'small-box-footer']); ?>
            </a>
        </div>
    </div>
</div>
    <!--buscador-->
        <div class="col-md-3 col-md-push-9">
            <div class="box box-default"><!-- filtro -->
                <div class="box-header with-border">
                    <h3 class="box-title">Buscar</h3>
                </div>
                <div class="box-body">
                    
                </div>
            </div>
        </div>
    <!--buscador-->
    <!--tabla usuarios-->
        <div class="col-md-9 col-md-pull-3">
            <div class="row">
                <div class="box">
                <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                                    <th scope="col"><?= $this->Paginator->sort('Nombre') ?></th>
                                    <th scope="col"><?= $this->Paginator->sort('Rut') ?></th>
                                    <th scope="col"><?= $this->Paginator->sort('Email') ?></th>
                                    <th scope="col"><?= $this->Paginator->sort('Teléfono') ?></th>
                                    <th scope="col" class="actions"><?= __('Acción') ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($instances as $instance): ?>
                                <tr>
                                    <td><?= $this->Number->format($instance->id) ?></td>
                                    <td><?= h($instance->name) ?></td>
                                    <td><?= h($instance->rut_enterprises) ?></td>
                                    <td><?= h($instance->email) ?></td>
                                    <td><?= h($instance->phone) ?></td>
                                    <td class="actions">
                                    <?= $this->Html->link(__('Detalles'), ['action' => 'view', $instance->id], ['class' => 'btn btn-success btn-sm']) ?>
                                    <?= $this->Html->link(__('Editar'), ['action' => 'edit', $instance->id], ['class' => 'btn btn-info btn-sm']) ?>
                                    <?= $this->Form->postLink(__('Eliminar'), ['action' => 'delete', $instance->id],  ['class' => 'btn btn-danger btn-sm'], ['confirm' => __('Are you sure you want to delete # {0}?', $instance->id)]) ?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>    
    <!--tabla usuarios-->   

src/Template/Instances/view.ctp
<div class="col-md-3">
    <div class="box box-primary">
        <div class="box-body box-profile">
           
            <h3 class="profile-username text-center"><?= h($instance->name) ?></h3>

            <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b><?= __('Nombre') ?></b> <a class="pull-right"><?= h($instance->name) ?></a>
                    </li>
                    <li class="list-group-item">
                        <b><?= __('Rut de la empresa') ?></b> <a class="pull-right"><?= h($instance->rut_enterprises) ?></a>
                    </li>
                    <li class="list-group-item">
                        <b><?= __('Email') ?></b> <a class="pull-right"><?= h($instance->email) ?></a>
                    </li>
                    <li class="list-group-item">
                        <b><?= __('Telefono') ?></b> <a class="pull-right"><?= h($instance->phone) ?></a>
                    </li>
                    <li class="list-group-item">
                        <b><?= __('Dirección') ?></b> <a class="pull-right"><?= h($instance->address) ?></a>
                    </li>
                    <li class="list-group-item">
                        <b><?= __('Contactos') ?></b> <a class="pull-right"><?= h($instance->contacts) ?></a>
                    </li>
                    <li class="list-group-item">
                        <b><?= __('Tipo de instancia') ?></b> <a class="pull-right"><?= $instance->type_instance->name?></a>
                    </li>
                    <li class="list-group-item">
                        <b><?= __('fecha') ?></b> <a class="pull-right"><?= h($instance->date) ?></a>
                    </li>
            </ul>
        </div>
    </div>
</div>
<div class="col-md-9">
    <div class="box">
        <div class="box-header with-border">
            
        </div>
            <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                            <th scope="col"><?= $this->Paginator->sort('Nombre') ?></th>
                            <th scope="col"><?= $this->Paginator->sort('Email') ?></th>
                            <th scope="col"><?= $this->Paginator->sort('Role') ?></th>
                    </tr>
                </thead>
                <tbody>
                        <? foreach($instance->users as $user): ?>
                    <tr>
                        <td><?= $this->Number->format($user->id) ?></td>
                            <td><?= $user->first_name ?></td>
                            <td><?= h($user->email) ?></td>
                            <td><?= h($user->roles_id) ?></td>
                    </tr>
                        <? endforeach; ?>
                </tbody>
            </table>

<div class="paginator">
    <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('Primero')) ?>
            <?= $this->Paginator->prev('< ' . __('Anterior')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('Siguiente') . ' >') ?>
            <?= $this->Paginator->last(__('Ultimo') . ' >>') ?>
    </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
</div>